// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/sunsunskibiz/wire/calculator"
)

// Injectors from wire.go:

func InitializeCalculator() calculator.Calculator {
	adder := calculator.NewAdder()
	calculatorCalculator := calculator.NewCalculator(adder)
	return calculatorCalculator
}
